#Login
POST http://localhost:9091/admin/login
Content-Type: application/json

{
    "email": "naphat@gmail.com",
    "password": "Nap007xHat",
    "rememberMe": false
}

###

#Forgot 
POST http://localhost:9091/api/auth/forgot-password
Content-Type: application/json

{
    "email": "naphat@gmail.com"
}

###

#Profile
GET http://localhost:9091/api/users/me
Authorization: Bearer 
###

#Register / Signup
POST http://localhost:9091/api/auth/local/register
Content-Type: application/json

{
    "username": "naphat",
    "email": "naphat@gmail.com",
    "password": "Nap007xHat"
}

