#Login
POST http://localhost:9091/admin/login
Content-Type: application/json

{
    "email": "naphat@gmail.com",
    "password": "Nap007xHat",
    "rememberMe": false
}

###

#Forgot 
GET http://localhost:9091/admin/forgot-password
Content-Type: application/json

{
    "email": "naphat@gmail.com"
}

###

#Profile
GET http://localhost:9091/admin/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzg3NjY5NTc0LCJleHAiOjE3OTAyNjE1NzR9.FlB7B7M-Yzsqf4an8cXOCnMRij0nHl-s-M1jVRuH9n8

###

#Register / Signup
GET http://localhost:9091/admin/register-admin
Content-Type: application/json

{
    "username": "naphat",
    "email": "naphat@gmail.com",
    "password": "Nap007xHat"
}

