services:
  db:
    image: postgres:16-alpine
    container_name: 69-s1-db
    ports:
      - 54327:5432
    environment:
      - POSTGRES_PASSWORD=Nap007xHat
      - POSTGRES_USER=naphat
      - POSTGRES_DB=naphat
    volumes:
      - ./data/data:/var/lib/postgresql/data
